server:
  port: 8081

spring:
  application:
    name: addition-service
  cache:
    type: simple

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.calculator: DEBUG