server:
  port: 8085

spring:
  application:
    name: history-service
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/calculator_history}
    username: ${DATABASE_USERNAME:calculator}
    password: ${DATABASE_PASSWORD:calculator123}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 1000ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.calculator: DEBUG
    org.hibernate.SQL: DEBUG